"""add background to leaderboard

Revision ID: 27b9cfbcc4ab
Revises: aefe2282fa4d
Create Date: 2026-03-18 11:53:29.848358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b9cfbcc4ab'
down_revision: Union[str, Sequence[str], None] = 'aefe2282fa4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('background', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'background')
    # ### end Alembic commands ###
